SELECT DISTINCT TRIM(CITY) AS CITY
FROM STATION
WHERE SUBSTR(UPPER(TRIM(CITY)), 1, 1) NOT IN ('A','E','I','O','U')
  AND SUBSTR(UPPER(TRIM(CITY)), LENGTH(TRIM(CITY)), 1) NOT IN ('A','E','I','O','U');
