SELECT distinct city
from station 
where upper(city) like ('A%A')
OR upper(city) like ('A%E')
OR upper(city) like ('A%I')
OR upper(city) like ('A%O')
OR upper(city)like ('A%U')
OR upper(city)like ('E%A')
OR upper(city)like ('E%E')
OR upper(city)like ('E%I')
OR upper(city)like ('E%O')
OR upper(city)like ('E%U')
OR upper(city)like ('I%A')
OR upper(city)like ('I%E')
OR upper(city)like ('I%I')
OR upper(city)like ('I%O')
OR upper(city)like ('I%U')
OR upper(city)like ('O%A')
OR upper(city)like ('O%E')
OR upper(city)like ('O%I')
OR upper(city)like ('O%O')
OR upper(city)like ('O%U')
OR upper(city)like ('U%A')
OR upper(city)like ('U%E')
OR upper(city)like ('U%I')
OR upper(city)like ('U%O')
OR upper(city)like ('U%U');
